language: python

python:
  - "3.7"
  - "3.8"
cache: pip

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry config virtualenvs.create false
  - poetry install --verbose

script:
  - poetry run black --check .

notifications:
  email: false